## application.yml (기본 설정)
spring:
  application:
    name: twelve-factor-app
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  
server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.example: ${LOG_LEVEL:INFO}