server:
  port: 50001

spring:
  application:
    name: user-ws
  profiles:
    active: local
  sleuth: 
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411/  
    discovery-client-enabled: false   
    sender.type: web           
  config:
    import: optional:configserver:http://localhost:8888       
  devtools:
    restart:
      enabled: true
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console        
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1

  redis:
    lettuce:
      pool:
        max-active: 8   # pool에 할당할수 있는 커넥션 최대수(default:8)
        max-idle: 8     # pool의 idle 커넥션 최대수(default:8)
        min-idle: 0     # pool의 idle 커넥션 최소수(default:0)
    host: localhost  # 
    port: 6379
    #password: 'new1234'   
      
management:
  endpoints:
    web:
      exposure:
        include: "*"      
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
      
feign:
  circuitbreaker:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 20000  # feign의 전역 timeout 설정 : 20초
        readTimeout: 20000
        loggerLevel: FULL ##basic
resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true # actuator 정보 노출을 위한 설정  
        ringBufferSizeInClosedState: 10 # 닫힌 상태에서의 호출 수로, 서킷을 열어야 할지 결정할 때 사용한다.                                            
        ringBufferSizeInHalfOpenState: 30 # 반열림 상태에서의 호출 수로, 서킷을 다시 열거나 닫힘 상태로 돌아갈지를 결정할 때 사용 한다.
        failureRateThreshold: 50 # 실패한 호출에 대한 임계값(백분율)으로 이 값을 초과하면 서킷이 열린다.
        waitDurationInOpenState: 10s # 열림 상태를 유지하는 시간, 해당 시간이후 반열림 상태로 변경된다.
        slidingWindowType: COUNT_BASED

    instances:
      order-ws:
        baseConfig: default
            
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance.instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}    

logging.level.org.springframework.cloud.sleuth: DEBUG

