# gateway/src/main/resources/application.yml
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

server:
  port: 80

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
