spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kirobo77/config-repo
          clone-on-start: true
          default-label: main
        health:
          repositories:
            myapp:
              label: main
              name: myapp
              profiles: development,production

server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh