server:
  port: 8888
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          #uri: http://git.cz-dev.container.kt.co.kr/82022949/config.git
          uri: https://github.com/kirobo77/config.git
          default-label: main
          skipSslValidation: true          
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true          
          